# Meta data
name:         admix-ui
authors:      bondli
description:  Build mobile apps with simple HTML, CSS, and JS components.

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
port:         4000
url:          http://bondli.github.io
